name: webtool_rep
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  percent_indicator: ^4.0.0
  provider: ^6.0.3
  cupertino_icons: ^1.0.5
  webview_flutter_web: ^0.1.0+1
  webview_flutter: ^3.0.4
  flutter_lints: ^2.0.0
  web_date_picker: ^1.0.0+3
  flutter_typeahead: ^4.1.1
  auto_size_widget: ^0.0.4
  file_picker_desktop: ^1.1.1
  image_picker: ^0.8.6
  file_picker: ^4.6.1
  http: ^0.13.5
  firebase_core: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

